<?php

namespace StareUp\Main\Bundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 
 /**
 *@DI\Service ("item.repository")
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBy(array $entity) {
        return $this->findBy($entity);
    }
}
