stare_up_main:
    resource: "@StareUpMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

itlized_social:
    resource: "@ItlizedSocialBundle/Resources/config/routing.yml"
    prefix:   /
